### PR TITLE
Update RabbitMessageBuilder.groovy

### PR DESCRIPTION
**Pull request by tamershahin**
If the resolve strategy is OWNER_FIRST the plugin cannot be used in controllers with cache-header plugin because it uses a closure like  this: 

withCacheHeaders {
			etag {
				getETag name: 'user', id: id
			}
			generate {
				def result = new RabbitMessageBuilder().rpc {
						exchange = 'core_rpc'
						routingKey = 'user.getUserData'
						body = [id: id]
						timeout = RabbitMessageBuilder.DEFAULT_TIMEOUT
					}
				renderResponse(result)
				cache 'short_term' // for history navigation (5 sec)
			}
		}

It needs to be DELEGATE_FIRST so the closure can refer to the RabbitMessageBuilder to write exchange and other properties.

Do you think it's possible to have a new plugin release if the pull request it's accepted?

### CODE REVIEW

**Comment by germanSancho** [comment]
+1!

**Comment by budjb** [comment]
I did not merge this because there was an additional case that needed to be changed.  I'm going to close the PR, but the change has been made.

**Comment by budjb** [comment]
Also, the plugin will be released in a few days.  The plugin itself has undergone an under-the-covers major refactor, and a significant amount of tests have been added.  I need to do some additional work on the documentation to make the transition easier for users.

**Comment by tamershahin** [comment]
Ok, Thank you! :)

**Pull request closed without merging**
