### PR TITLE
Grails 3.1.x

### PR DESCRIPTION
**Pull request by olliefreeman**
Updated codebase to grails 3.1.1 and setup to handle both groovy and yml configuration.

To allow an easier differentiation between grails 2 and grails 3 code I have renamed the grails project `rabbitmq-native3` and then due to changes incremented the version to 3.1.3,

also may not want to accept the change to the README file as the build shield points at my Travis.

### CODE REVIEW

**Comment by budjb** [comment]
Thanks for the PR. I haven't forgotten about it. I'm working on finishing up another plugin for a Grails 3 release and I'll be focusing on this when that's done.

**Comment by olliefreeman** [comment]
no worries, 

So I could make use of it i have published it into my bintray repo at

https://bintray.com/olliefreeman/maven/rabbitmq-native3/view

I may have made more updates since submitting the PR, if you let me know when you're about to start looking at it I'll make sure everything I've done, and is relevant, is in the PR

**Comment by budjb** [comment]
I'm getting ready to give this plugin some focus. You mentioned there are some additional updates you might add to this PR. Before I pull this in, do you want to take another look?

**Comment by olliefreeman** [comment]
All updates are in, I have updated to grails 3.1.5, and the test on the branch should pass.

Please note there are a few url pointers to my travis repo in the README and also in the build file to send the jars to my bintray repo.

**Comment by budjb** [comment]
No problem, I'll merge the PR and change up the bits I need to. Thanks!

**Comment by budjb** [comment]
Hey Ollie, thanks for the pull request! I made 2 design decisions with this PR and made some changes, so I thought you should know about them if you end up using the official release of the plugin.
- I wanted to maintain JDK 1.7 compatibility, so I reverted back to `Calendar` from `OffsetDateTime`.
- I thought the YAML configuration may be easier to deal with if it were a bit more flat and users did not need to rely on naming conventions, so I refactored how the YAML configuration parsing worked. You can see an example [here](https://github.com/budjb/grails-rabbitmq-native/blob/grails-3.0.x/grails-app/conf/application.yml#L12). The downside is that information needs to be duplicated, but I thought it was easier to read.

**Comment by olliefreeman** [comment]
I'll check these out at some point, the code base this is deployed in is on its last month of development so wont be changing anything soon. Interesting choice to support 1.7 as Oracle have stopped releasing any further updates, but no harm i guess. 

I'll have to look into the sample YAMLs to see what you mean, 

but more importantly thank you for the plugin in the first place, saved a whole heap of work and its power and simplicity is fantastic, glad to have been able to help out.

**Comment by budjb** [comment]
Thanks for submitting! All my plugins are rather self-serving, as we use them on my team where I work, so I'm always thrilled when others find use of them.

**Comment by olliefreeman** [comment]
Well it's being used by Oxford University BRC Informatics in several projects and being deployed into a system built for Genomics England Ltd.....definitely found a use for it

**Pull request merged**
